# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20170927_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminderTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
