# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20170927_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminderTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
