# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_auto_20170927_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=100),
        ),
    ]
